### ISSUE TITLE
[Lineage OS][16.0] Bug: Various Fixes module does not work

### ISSUE THREAD

**Issue by Giv314** [MontanaDevelopment/Issue-Tracker#1]
**Describe the bug**
The "Various fixes for Moto G5/G5S" module does not install in this Rom, actually, I don't know if it is a bug or something, so, I attached the log here.

**To Reproduce**
1. Install module
2. Magisk print a message "Press a vol key"
3. "Module only for Moto G5 and Moto G5S. Aborting."

**Expected behavior**
Install Module and restart system with the module applied.

**Screenshots**
Attached 

**Logs**
Attached

**Some details about your OS:**
 - OS: [LineageOS 16]
 - Version [2019/07/07]
 - Mods [Magisk]

**Additional context**
Nothing.
![Screenshot_20190805-001657_Magisk_Manager](https://user-images.githubusercontent.com/53719063/62436545-6436fe80-b716-11e9-86ad-f53c6fe55d42.png)
[magisk_install_log_2019-08-04T23:23:29Z.log](https://github.com/MontanaDevelopment/Issue-Tracker/files/3465805/magisk_install_log_2019-08-04T23.23.29Z.log)

**Comment by JarlPenguin** [comment]
Issue should be fixed in a few hours while the Magisk module updates in the repos.
