### ISSUE TITLE
[leanageos][16] Bug: Photoscan and panoramas freezer and crash when take pictures

### ISSUE THREAD

**Issue by Aryx0** [MontanaDevelopment/Issue-Tracker#2]
**describe the bug**
hello, I noticed a problem on all the roms I used.  Google apps that use the gyro freezer and crash in progress.  This is the case for photoscan, photosphere and panorama.  

**To reproduce**
Install photoscan and scan a photo, the app will crash at the first or second point

**Infos**
Los 16
Moto g5s montana 
Twrp, magisk 19

**Screenshots**
![Screenshot_20190809-133748_PhotoScan](https://user-images.githubusercontent.com/45895096/62787098-44ac2700-bac4-11e9-900c-c0741ed8935e.png)
![Screenshot_20190809-133850_Appareil_photo](https://user-images.githubusercontent.com/45895096/62787121-4e358f00-bac4-11e9-81b0-f5a658e99c6d.png)

**Comment by wiktorek140** [comment]
On gcam it probably never work correctly

**Comment by JarlPenguin** [comment]
GCam bug.

**Comment by Aryx0** [comment]
How to find logs ?

**Comment by JarlPenguin** [comment]
> How to find logs ?

Connect your device to a PC, ensure adb is installed.

In a terminal type `adb logcat > logs.log` and send the logs here.
