### ISSUE TITLE
[ROM][9.0.0_r46][MONTANA] LineageOS 16.0 [UNOFFICIAL][TREBLE][0.12]] Bug: some app crash while starting

### ISSUE THREAD

**Issue by DanMornill** [MontanaDevelopment/Issue-Tracker#3]
Whatsapp, Opera and Firefox are crashing when they try to start.
Chrome is usable, but also crashes when going into parameters.

**To Reproduce**
Simply try to launch the app again.

**Expected behavior**
Should work fine, as in 0.11

 - OS: LineageOS 16
 - Version 0.12
 - Mods none

**Comment by JarlPenguin** [comment]
Please include logs, ping me when you do
