### ISSUE TITLE
[Lineage OS][16.0] Bug:  cLock weather only works with USB connected into PC

### ISSUE THREAD

**Issue by Giv314** [MontanaDevelopment/Issue-Tracker#4]
**Describe the bug**
I installed OpenWeatherProvider 16.0 in Lineage as a weather provider in cLock, but when I try to update the weather statistics, it doesn't update, and when I try to change the city in "Widget settings" and "Wheather panel", it displays the message: "Cannot retrieve location!".
![Screenshot_20190820-170738_cLock](https://user-images.githubusercontent.com/53719063/63381294-c0cd2700-c36e-11e9-8dc1-9e273f269cd3.png)
The weirdest thing is, it works when I connect USB cable on my PC, and I have the possibility to change the city name, so it works when USB is plugged:
![Screenshot_20190820-170810_cLock](https://user-images.githubusercontent.com/53719063/63381387-ed813e80-c36e-11e9-9d6b-edea3dbf7875.png)

**To Reproduce**
1. Install "OpenWheatherMap 16.0" (It's available on Lineage OS Extras website)
2. Select "OpenWheatermap" as Wheather provider in "Clock - Widget Settings - Wheater panel - Wheater source."
3. Create an API key
4. Activate "Use a custom location" button and put your city name (It doesn't work, except when USB is connect to PC)

**Expected behavior**
That the weather provider in cLock works without USB connected mandatorily.

**Logs**
[log.log](https://github.com/MontanaDevelopment/Issue-Tracker/files/3522442/log.log)

**Some details about your OS:**
 - OS: [LineageOS 16]
 - Version [e.g. 2019/08/12]
 - Mods [Magisk]

**Comment by JarlPenguin** [comment]
I need someone to confirm, since openweathermap doesn't load here

**Comment by Giv314** [comment]
Hey Jarl, bug was fixed :) I guess they updated the repos

**Comment by JarlPenguin** [comment]
Thanks for reporting :)
