### ISSUE TITLE
[Lineage OS][15.1 Test Build #5]

### ISSUE THREAD

**Issue by Giv314** [MontanaDevelopment/Issue-Tracker#5]
**Describe the bug**
I found 3 bugs in this Build:
1. Camera app stops recording when I touch the device (Try to take a screenshot)
2.  Cannot transfer big files to PC (libmtp error)
3. Mobile data works only if restarting the phone
4. After rebooting three or five times, device stops booting (shows bootlogo, but doesn't load bootanimation and gets a bootloop)

**To Reproduce**
Bug #1: Open Lineage Camera app, then, put in Recorder mode, tap in recorder button than it starts recording. When you touch the device to adjust focus, the app freezes and crashes after some seconds
Bug #2: I recorded 2 audios: one of them had 398MB and the other one, 410MB. When I transfer these audios to my PC, I get a "libmtp error". However, if I copy these 2 audios to my Micro SD Card, I can copy them to my PC. I can copy them separated too, first one and the other next. This means that I can't copy them together, but separated. This error is fixed when I activate the "USB Debugging" in developer settings
Bug #3: This bugs only happens when the Rom boots in the first time. If you reboot, this error is fixed.
Bug #4: Configuring device (installing Magisk and some apps) and rebooting a right number of times, device dies, shows bootlogo, but not Lineage Bootanimation.

**Screenshots**
First boot: 
![Screenshot_20191010-192134_Call_Management](https://user-images.githubusercontent.com/53719063/66707662-47bcd100-ed1a-11e9-95ae-50a638d0ea90.png)
![Screenshot_20191010-192259_Trebuchet](https://user-images.githubusercontent.com/53719063/66707663-4db2b200-ed1a-11e9-923c-0ee29a0d50df.png)

Second boot:
![Screenshot_20191012-135336_Settings](https://user-images.githubusercontent.com/53719063/66707564-cca6eb00-ed18-11e9-8113-04bd0cd41378.png)

Camera:
![Camera](https://user-images.githubusercontent.com/53719063/66707668-6ae78080-ed1a-11e9-9890-82b09b4e938d.png)
 

**Logs**
1: [log.log](https://github.com/MontanaDevelopment/Issue-Tracker/files/3721144/log.log)
2: (Camera issue, Permissive mode): [log5.log](https://github.com/MontanaDevelopment/Issue-Tracker/files/3746880/log5.log)
3: Bootloop issue: 
[log6.log](https://github.com/MontanaDevelopment/Issue-Tracker/files/3746881/log6.log)

**Some details about your OS:**
 - OS: [LineageOS 15]
 - Version [2019/10/10]
 - Mods [Magisk and I use Migrate to restore my apps]

**Comment by JarlPenguin** [comment]
Did you try without using Migrate or Magisk? Also, I'd appreciate it if you attached different logs for different problems.

**Comment by Giv314** [comment]
> Did you try without using Migrate or Magisk? Also, I'd appreciate it if you attached different logs for different problems.

Yes, actually I installed these mods after the first boot, but unfortunately I didn't get logs :( Well, I will test Build #4, but at this time, I will attach different logs.

**Comment by Giv314** [comment]
So, I tested build #5 and recording videos works, howerver when device is touched, the camera app crashes and shows this message: 
![Uploading Screenshot_20191012-142012_Gallery.png…]()

About the logs, I will attach some of them; well, here is the log when I made the first boot (RIL doesn't work): 
[log1.log](https://github.com/MontanaDevelopment/Issue-Tracker/files/3721329/log1.log)

The second log, when I reboot the device and RIL started to working: 
[log2.log](https://github.com/MontanaDevelopment/Issue-Tracker/files/3721331/log2.log)

The third log, that I attached when the device was recording, then I tapped on screen and the app crashed: 
[log3.log](https://github.com/MontanaDevelopment/Issue-Tracker/files/3721332/log3.log)

Obs: At this time, I didn't use mods like Magisk, gapps or Migrate.

**Comment by wiktorek140** [comment]
Bug1: i can confirm it on my build so i will check that.

Bug 2: try use different usb port or shorter cable. I will try to do something with that but i cannot promise anything rn.

Bug 3: did you check other sim cards?

**Comment by Giv314** [comment]
> Bug1: i can confirm it on my build so i will check that.
> 
> Bug 2: try use different usb port or shorter cable. I will try to do something with that but i cannot promise anything rn.
> 
> Bug 3: did you check other sim cards?

Using different USB port fixed the problem. Using another SIM Card didn't fix but he recognizes the carrier. I use 2 different SIM cards.
[log4.log](https://github.com/MontanaDevelopment/Issue-Tracker/files/3722047/log4.log)

**Comment by Giv314** [comment]
UPDATE: I got a bootloop after configuring my device with Magisk and apps. See third log attached.

**Comment by Giv314** [comment]
Hey, Issues were fixed in last LineageOS 15.1 Build! So, I will close this issue. Thanks for your support.
